;/*FB_PKG_DELIM*/

__d("useIGDSToaster",["IGDSPrivateToasterContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){return h(d("IGDSPrivateToasterContext").IGDSPrivateToasterContext)}g["default"]=a}),98);
__d("useWWWIGStoriesLogging",["PolarisLogPageView","PolarisReactRedux","polarisStorySelectors","react","useCometRouterState"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useEffect,i=b.useRef;function a(){var a=d("PolarisReactRedux").useSelector(d("polarisStorySelectors").getCurrentPostId),b=c("useCometRouterState")(),e=i(null);h(function(){b!=null&&a!=null&&(e==null?void 0:e.current)!=null&&e.current!==a&&c("PolarisLogPageView")(b),e.current=a},[a,b])}g["default"]=a}),98);
__d("usePolarisStoriesProviderDisableNewPlayback",["PolarisConfig","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useEffect;function a(a,b,c,e){var f=a.hasFocus,g=a.isBugNubActive,i=a.isCaptionModalActive,j=a.isCloseFriendsDialogActive,k=a.isExclusiveStoryDialogActive,l=a.isHidden,m=a.isHighlightsTrayActive,n=a.isKeyboardActive,o=a.isModalActive,p=a.isPaused,q=a.isStoryShareSheetActive,r=a.isStoryViewerListActive,s=a.isTransitioning,t=a.isUnfollowModalActive;h(function(){var a=g||k||j||n||o||p||q||r||m||s||t||i||l||d("PolarisConfig").isIOS()&&!f||b!=null||c;e({isPlaybackDisabled:a})},[f,g,j,k,l,n,o,p,q,r,m,s,t,i,c,e,b])}g["default"]=a}),98);
__d("PolarisStoriesProvider.react",["PolarisReactRedux","PolarisRelationshipTypes","PolarisStoriesContext","nullthrows","polarisRelationshipSelectors","polarisStorySelectors","react","usePolarisStoriesProviderDisableNewPlayback","useWWWIGStoriesLogging"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");e=d("react");var i=e.useCallback,j=e.useContext,k=e.useEffect,l=e.useMemo,m=e.useState;function a(){return j(d("PolarisStoriesContext").StoriesContext)}function b(a){var b=a.children,e=a.initialState,f=c("nullthrows")(d("PolarisReactRedux").useSelector(d("polarisStorySelectors").getCurrentPostAuthor));a=d("PolarisReactRedux").useSelector(function(a){return d("polarisRelationshipSelectors").getRelationship(a.relationships,f.id)});var g=a.followedByViewer.state===d("PolarisRelationshipTypes").FOLLOW_STATUS_FOLLOWING,j=d("PolarisReactRedux").useSelector(function(a){return a.displayProperties.viewportHeight});a=l(function(){return babelHelpers["extends"]({},d("PolarisStoriesContext").defaultContext,e,{isInitiallyFollowedByViewer:g,viewerHeight:j})},[g,e,j]);a=m(a);var n=a[0],o=a[1];a=d("PolarisReactRedux").useSelector(d("polarisStorySelectors").isFromPreviousFullscreenSession);var p=d("PolarisReactRedux").useSelector(function(a){return a.stories.isAppAttributionOpen}),q=d("PolarisReactRedux").useSelector(function(a){return a.stories.tappedObjectId}),r=i(function(a){return o(function(b){return babelHelpers["extends"]({},b,a)})},[]),s=l(function(){return babelHelpers["extends"]({},n,{updateStoriesContext:r})},[n,r]);c("useWWWIGStoriesLogging")();var t=a||p;c("usePolarisStoriesProviderDisableNewPlayback")(n,q,t,r);k(function(){r({isResumeOverlayActive:t})},[t,r]);k(function(){r({hasFocus:document.hasFocus(),isHidden:document.hidden!=null?document.hidden:!1})},[r]);return h.jsx(d("PolarisStoriesContext").StoriesContext.Provider,{value:s,children:b})}b.displayName=b.name+" [from "+f.id+"]";e=h.memo(b);g.useStoriesContext=a;g.StoriesContextProvider=e}),98);
__d("PolarisHideNativeAppBanner",["PolarisBatchDOM","PolarisConfig","emptyFunction"],(function(a,b,c,d,e,f,g){"use strict";function a(a){a===void 0&&(a=c("emptyFunction")),d("PolarisConfig").isIOS()&&d("PolarisBatchDOM").mutate(function(){window.setTimeout(function(){window&&document.body&&(window.scrollTo(0,document.body.scrollHeight),a())},0)})}g.hideNativeAppBanner_HACK=a}),98);
__d("PolarisPostShareUtils",["PolarisLinkBuilder","nullthrows","polarisGetPostFromGraphMediaInterface"],(function(a,b,c,d,e,f,g){"use strict";function a(a,b){return(b==null?void 0:b.isPrivate)!==!0&&a.viewerCanReshare===!0}function b(a){return a.igMediaSharingDisabled!==!0}function h(a){var b=c("nullthrows")(a.code);return d("polarisGetPostFromGraphMediaInterface").isClipsPost(a)?d("PolarisLinkBuilder").buildClipsMediaLink(b):d("PolarisLinkBuilder").buildMediaLink(b)}function e(a){var b;b=((b=a.shareIds)==null?void 0:b.copy)||"";a=window.location.origin+h(a);return b.length>0?a+"?utm_source=ig_web_copy_link&igshid="+b:a+"?utm_source=ig_web_copy_link"}g.getIsShareable=a;g.getIsMediaQuarantinedForShare=b;g.getShareURL=h;g.getCopyUrl=e}),98);
__d("getImageSourceURLFromImageish",[],(function(a,b,c,d,e,f){"use strict";function a(a){if(typeof a==="string")return a;return a!=null&&typeof a==="object"&&(!a.sprited&&a.uri&&typeof a.uri==="string")?a.uri:""}f["default"]=a}),66);
__d("asset",[],(function(a,b,c,d,e,f){function a(){for(var a=arguments.length,b=new Array(a),c=0;c<a;c++)b[c]=arguments[c];throw new Error("asset("+b.join(",")+"): Unexpected asset reference")}e.exports=a}),null);